private void populateAndShowProblemDetails(hackthon.codechef.chefonphone.data.Problem problem) {
    hackthon.codechef.chefonphone.data.Problem _CVAR1 = problem;
     _CVAR2 = _CVAR1.getProblemName();
    java.lang.String problemNameStr = "Problem Name : " + _CVAR2;
    java.lang.String _CVAR3 = problemNameStr;
    android.widget.TextView _CVAR0 = problemName;
    android.text.Spanned _CVAR4 = android.text.Html.fromHtml(_CVAR3);
    _CVAR0.setText(_CVAR4);
    hackthon.codechef.chefonphone.data.Problem _CVAR6 = problem;
     _CVAR7 = _CVAR6.getProblemCode();
    java.lang.String problemCode_ContestStr = "<br>Problem Code:</br> " + _CVAR7;
    java.lang.String _CVAR8 = problemCode_ContestStr;
    android.widget.TextView _CVAR5 = problemCode_contest;
    android.text.Spanned _CVAR9 = android.text.Html.fromHtml(_CVAR8);
    _CVAR5.setText(_CVAR9);
    hackthon.codechef.chefonphone.data.Problem _CVAR11 = problem;
     _CVAR12 = _CVAR11.getDateAdded();
    java.lang.String dateAddedStr = "<br>Date Added:<br> " + _CVAR12;
    java.lang.String _CVAR13 = dateAddedStr;
    android.widget.TextView _CVAR10 = dateAdded;
    android.text.Spanned _CVAR14 = android.text.Html.fromHtml(_CVAR13);
    _CVAR10.setText(_CVAR14);
    hackthon.codechef.chefonphone.data.Problem _CVAR16 = problem;
     _CVAR17 = _CVAR16.getSourceSizeLimit();
    java.lang.String sourceSizeLimitStr = "<br>Source Size Limit:<br> " + _CVAR17;
    java.lang.String _CVAR18 = sourceSizeLimitStr;
    android.widget.TextView _CVAR15 = sourceSizeLimit;
    android.text.Spanned _CVAR19 = android.text.Html.fromHtml(_CVAR18);
    _CVAR15.setText(_CVAR19);
    hackthon.codechef.chefonphone.data.Problem _CVAR21 = problem;
     _CVAR22 = _CVAR21.getMaxTimeLimit();
    java.lang.String maxTimeLimitStr = "<br>Max Time Limit:<br> " + _CVAR22;
    java.lang.String _CVAR23 = maxTimeLimitStr;
    android.widget.TextView _CVAR20 = maxTimeLimit;
    android.text.Spanned _CVAR24 = android.text.Html.fromHtml(_CVAR23);
    _CVAR20.setText(_CVAR24);
    hackthon.codechef.chefonphone.data.Problem _CVAR26 = problem;
     _CVAR27 = _CVAR26.getChallengeType();
    java.lang.String challengeTypeStr = "<br>Challenge Type:<br> " + _CVAR27;
    java.lang.String _CVAR28 = challengeTypeStr;
    android.widget.TextView _CVAR25 = challengeType;
    android.text.Spanned _CVAR29 = android.text.Html.fromHtml(_CVAR28);
    _CVAR25.setText(_CVAR29);
    hackthon.codechef.chefonphone.data.Problem _CVAR31 = problem;
     _CVAR32 = _CVAR31.getSuccessfulSubmissions();
    java.lang.String successfulSubmissionsStr = "<br>Successful Submissions:<br> " + _CVAR32;
    java.lang.String _CVAR33 = successfulSubmissionsStr;
    android.widget.TextView _CVAR30 = successfulSubmissions;
    android.text.Spanned _CVAR34 = android.text.Html.fromHtml(_CVAR33);
    _CVAR30.setText(_CVAR34);
    hackthon.codechef.chefonphone.data.Problem _CVAR36 = problem;
     _CVAR37 = _CVAR36.getAuthor();
    java.lang.String authorStr = "<br>Author:<br> " + _CVAR37;
    java.lang.String _CVAR38 = authorStr;
    android.widget.TextView _CVAR35 = author;
    android.text.Spanned _CVAR39 = android.text.Html.fromHtml(_CVAR38);
    _CVAR35.setText(_CVAR39);
    problemBody.addStyleSheet(new br.tiagohm.markdownview.css.styles.Github());
    hackthon.codechef.chefonphone.data.Problem _CVAR41 = problem;
     _CVAR42 = _CVAR41.getBody();
    android.text.Spanned _CVAR43 = android.text.Html.fromHtml(_CVAR42);
    br.tiagohm.markdownview.MarkdownView _CVAR40 = problemBody;
     _CVAR44 = _CVAR43.toString();
    _CVAR40.loadMarkdown(_CVAR44);
    problemView.setVisibility(android.view.View.VISIBLE);
    ideLoaderProgress.setVisibility(android.view.View.GONE);
    isProblemViewShowing = true;
}