public void addShoppingList(android.view.View v) {
    java.lang.String _CVAR1 = "";
    java.lang.String _CVAR0 = "addShoppingListMinute";
    java.lang.String _CVAR2 = start.getCurrentMinute() + _CVAR1;
    android.util.Log.d(_CVAR0, _CVAR2);
    android.util.Log.d("addShoppingListHour", start.getCurrentHour() + "");
    java.util.Calendar start_time = new java.util.GregorianCalendar();
    android.widget.TimePicker _CVAR5 = start;
    java.util.Calendar _CVAR3 = start_time;
    int _CVAR4 = java.util.Calendar.MINUTE;
    java.lang.Integer _CVAR6 = _CVAR5.getCurrentMinute();
    _CVAR3.add(_CVAR4, _CVAR6);
    start_time.add(java.util.Calendar.HOUR_OF_DAY, start.getCurrentHour());
    android.util.Log.d("addShoppingListTimeAsString", start_time.toString());
    java.util.Calendar end_time = new java.util.GregorianCalendar();
    android.widget.TimePicker _CVAR9 = end;
    java.util.Calendar _CVAR7 = end_time;
    int _CVAR8 = java.util.Calendar.MINUTE;
    java.lang.Integer _CVAR10 = _CVAR9.getCurrentMinute();
    _CVAR7.add(_CVAR8, _CVAR10);
    end_time.add(java.util.Calendar.HOUR_OF_DAY, end.getCurrentHour());
    android.widget.TimePicker _CVAR12 = start;
    android.widget.TimePicker _CVAR14 = start;
    aarne.kyppo.shoplistnotifier.app.ShoppingList _CVAR11 = sl;
    java.lang.Integer _CVAR13 = _CVAR12.getCurrentHour();
    java.lang.Integer _CVAR15 = _CVAR14.getCurrentMinute();
    _CVAR11.setStart(_CVAR13, _CVAR15);
    aarne.kyppo.shoplistnotifier.app.ShoppingList sl = new aarne.kyppo.shoplistnotifier.app.ShoppingList();
    android.widget.TimePicker _CVAR17 = end;
    android.widget.TimePicker _CVAR19 = end;
    aarne.kyppo.shoplistnotifier.app.ShoppingList _CVAR16 = sl;
    java.lang.Integer _CVAR18 = _CVAR17.getCurrentHour();
    java.lang.Integer _CVAR20 = _CVAR19.getCurrentMinute();
    _CVAR16.setEnd(_CVAR18, _CVAR20);
    sl.setTitle(title.getText().toString());
    aarne.kyppo.shoplistnotifier.app.DBHelper helper = new aarne.kyppo.shoplistnotifier.app.DBHelper(this);
    helper.addShoppingList(sl);
    int id = helper.getEarliestShoppingListID();
    android.util.Log.d("EARLIEST ID", id + "");
    helper = null;
    android.content.Intent i = new android.content.Intent(this, aarne.kyppo.shoplistnotifier.app.ShoppingListActivity.class);
    i.putExtra("earliest", id);
    startActivity(i);
}