void createRanking() {
    android.util.Log.i("PlayersRanking", "createRanking");
    android.widget.TableRow row = new android.widget.TableRow(this);
    row.setMinimumWidth(table.getWidth());
    row.setMinimumHeight(table.getHeight() / (players.length + 3));
    table.addView(row);
    row = new android.widget.TableRow(this);
    row.setMinimumWidth(table.getWidth());
    row.setMinimumHeight(table.getHeight() / (players.length + 3));
    android.widget.TextView _CVAR1 = tv;
     _CVAR2 = getApplicationContext();
    void _CVAR3 = R.style.RankingTitle;
    _CVAR1.setTextAppearance(_CVAR2, _CVAR3);
    tv.setText(" ");
    tv.setGravity(android.view.Gravity.RIGHT);
    tv.setGravity(android.view.Gravity.BOTTOM);
    tv.setWidth((table.getWidth() * 3) / 8);
    row.addView(tv);
    tv = new android.widget.TextView(this);
    tv.setText("Player");
    android.widget.TextView _CVAR5 = tv;
     _CVAR6 = getApplicationContext();
    void _CVAR7 = R.style.RankingTitle;
    _CVAR5.setTextAppearance(_CVAR6, _CVAR7);
    tv.setGravity(android.view.Gravity.BOTTOM);
    tv.setWidth((table.getWidth() * 3) / 8);
    row.addView(tv);
    tv = new android.widget.TextView(this);
    tv.setText(" ELO");
    android.widget.TextView _CVAR9 = tv;
     _CVAR10 = getApplicationContext();
    void _CVAR11 = R.style.RankingTitle;
    _CVAR9.setTextAppearance(_CVAR10, _CVAR11);
    tv.setGravity(android.view.Gravity.BOTTOM);
    tv.setWidth((table.getWidth() * 2) / 8);
    row.addView(tv);
    table.addView(row);
    de.fz_juelich.inm.kicker.kicker.PlayersRanking _CVAR0 = this;
    de.fz_juelich.inm.kicker.kicker.PlayersRanking _CVAR4 = _CVAR0;
    de.fz_juelich.inm.kicker.kicker.PlayersRanking _CVAR8 = _CVAR4;
    de.fz_juelich.inm.kicker.kicker.PlayersRanking _CVAR12 = _CVAR8;
    de.fz_juelich.inm.kicker.kicker.PlayersRanking _CVAR16 = _CVAR12;
    de.fz_juelich.inm.kicker.kicker.PlayersRanking _CVAR20 = _CVAR16;
    android.widget.TextView tv = new android.widget.TextView(_CVAR20);
    for (int i = 0; i < players.length; i++) {
        row = new android.widget.TableRow(this);
        row.setMinimumWidth(table.getWidth());
        row.setMinimumHeight(table.getHeight() / (players.length + 3));
        tv = new android.widget.TextView(this);
        android.widget.TextView _CVAR13 = tv;
         _CVAR14 = getApplicationContext();
        void _CVAR15 = R.style.RankingEntry;
        _CVAR13.setTextAppearance(_CVAR14, _CVAR15);
        tv.setText((i + 1) + ".");
        tv.setGravity(android.view.Gravity.CENTER);
        tv.setWidth((table.getWidth() * 3) / 8);
        row.addView(tv);
        tv = new android.widget.TextView(this);
        android.widget.TextView _CVAR17 = tv;
         _CVAR18 = getApplicationContext();
        void _CVAR19 = R.style.RankingEntry;
        _CVAR17.setTextAppearance(_CVAR18, _CVAR19);
        tv.setText(players[i].name);
        tv.setWidth((table.getWidth() * 3) / 8);
        row.addView(tv);
        tv = new android.widget.TextView(this);
        android.widget.TextView _CVAR21 = tv;
         _CVAR22 = getApplicationContext();
        void _CVAR23 = R.style.RankingEntry;
        _CVAR21.setTextAppearance(_CVAR22, _CVAR23);
        tv.setText(" " + players[i].elo);
        tv.setWidth((table.getWidth() * 2) / 8);
        row.addView(tv);
        if ((i % 2) == 0) {
            row.setBackgroundColor(android.graphics.Color.LTGRAY);
        }
        table.addView(row);
    }
}