private android.widget.LinearLayout getInsight(java.lang.String topic, java.lang.String objective, java.lang.String introduction, java.lang.String questions, java.lang.String textassignment) {
    // TODO Auto-generated method stub
    android.widget.LinearLayout parentLinearLayout = new android.widget.LinearLayout(context);
    android.widget.LinearLayout.LayoutParams parentLayoutParams = new android.widget.LinearLayout.LayoutParams(android.widget.LinearLayout.LayoutParams.MATCH_PARENT, android.widget.LinearLayout.LayoutParams.MATCH_PARENT);
    parentLinearLayout.setLayoutParams(parentLayoutParams);
    parentLinearLayout.setOrientation(android.widget.LinearLayout.VERTICAL);
    android.content.Context _CVAR0 = context;
    android.widget.TextView topicTextView = new android.widget.TextView(_CVAR0);
    android.widget.TextView _CVAR1 = topicTextView;
    android.content.Context _CVAR2 = context;
    int _CVAR3 = android.R.style.TextAppearance_Medium;
    _CVAR1.setTextAppearance(_CVAR2, _CVAR3);
    topicTextView.setTextColor(android.graphics.Color.parseColor("#691A99"));
    topicTextView.setTypeface(null, android.graphics.Typeface.BOLD);
    topicTextView.setText(topic);
    topicTextView.setTextSize(23);
    android.widget.LinearLayout.LayoutParams topicLayoutParams = new android.widget.LinearLayout.LayoutParams(android.widget.LinearLayout.LayoutParams.WRAP_CONTENT, android.widget.LinearLayout.LayoutParams.WRAP_CONTENT);
    topicLayoutParams.setMargins(0, 3, 0, 5);
    android.content.Context _CVAR4 = context;
    android.widget.TextView objectiveTextView = new android.widget.TextView(_CVAR4);
    android.widget.TextView _CVAR5 = objectiveTextView;
    android.content.Context _CVAR6 = context;
    int _CVAR7 = android.R.style.TextAppearance_Medium;
    _CVAR5.setTextAppearance(_CVAR6, _CVAR7);
    objectiveTextView.setTextColor(android.graphics.Color.parseColor("#8E24AA"));
    objectiveTextView.setTypeface(null, android.graphics.Typeface.BOLD);
    objectiveTextView.setText("Objective");
    android.widget.TextView objectiveContentTextView = new android.widget.TextView(context);
    objectiveContentTextView.setText(objective);
    objectiveContentTextView.setTextColor(android.graphics.Color.parseColor("#000000"));
    objectiveContentTextView.setLayoutParams(topicLayoutParams);
    android.content.Context _CVAR8 = context;
    android.widget.TextView introductionTextView = new android.widget.TextView(_CVAR8);
    android.widget.TextView _CVAR9 = introductionTextView;
    android.content.Context _CVAR10 = context;
    int _CVAR11 = android.R.style.TextAppearance_Medium;
    _CVAR9.setTextAppearance(_CVAR10, _CVAR11);
    introductionTextView.setText("Introduction");
    introductionTextView.setTextColor(android.graphics.Color.parseColor("#8E24AA"));
    introductionTextView.setTypeface(null, android.graphics.Typeface.BOLD);
    android.widget.TextView introContentTextView = new android.widget.TextView(context);
    introContentTextView.setText(introduction);
    introContentTextView.setTextColor(android.graphics.Color.parseColor("#000000"));
    introContentTextView.setLayoutParams(topicLayoutParams);
    android.content.Context _CVAR12 = context;
    android.widget.TextView questionsTextView = new android.widget.TextView(_CVAR12);
    android.widget.TextView _CVAR13 = questionsTextView;
    android.content.Context _CVAR14 = context;
    int _CVAR15 = android.R.style.TextAppearance_Medium;
    _CVAR13.setTextAppearance(_CVAR14, _CVAR15);
    questionsTextView.setText("Questions");
    questionsTextView.setTextColor(android.graphics.Color.parseColor("#8E24AA"));
    questionsTextView.setTypeface(null, android.graphics.Typeface.BOLD);
    android.widget.TextView questionsContentTextView = new android.widget.TextView(context);
    questionsContentTextView.setText(questions);
    questionsContentTextView.setTextColor(android.graphics.Color.parseColor("#000000"));
    questionsContentTextView.setLayoutParams(topicLayoutParams);
    android.content.Context _CVAR16 = context;
    android.widget.TextView activityTextView = new android.widget.TextView(_CVAR16);
    android.widget.TextView _CVAR17 = activityTextView;
    android.content.Context _CVAR18 = context;
    int _CVAR19 = android.R.style.TextAppearance_Medium;
    _CVAR17.setTextAppearance(_CVAR18, _CVAR19);
    activityTextView.setText("Activity");
    activityTextView.setTextColor(android.graphics.Color.parseColor("#8E24AA"));
    activityTextView.setTypeface(null, android.graphics.Typeface.BOLD);
    android.widget.TextView activityContentTextView = new android.widget.TextView(context);
    activityContentTextView.setText(activity);
    activityContentTextView.setTextColor(android.graphics.Color.parseColor("#000000"));
    activityContentTextView.setLayoutParams(topicLayoutParams);
    android.content.Context _CVAR20 = context;
    android.widget.TextView testAssignmentTextView = new android.widget.TextView(_CVAR20);
    android.widget.TextView _CVAR21 = testAssignmentTextView;
    android.content.Context _CVAR22 = context;
    int _CVAR23 = android.R.style.TextAppearance_Medium;
    _CVAR21.setTextAppearance(_CVAR22, _CVAR23);
    testAssignmentTextView.setText("Test/Assignment");
    testAssignmentTextView.setTextColor(android.graphics.Color.parseColor("#8E24AA"));
    testAssignmentTextView.setTypeface(null, android.graphics.Typeface.BOLD);
    android.widget.TextView testAssignmentContentTextView = new android.widget.TextView(context);
    testAssignmentContentTextView.setText(textassignment);
    testAssignmentContentTextView.setTextColor(android.graphics.Color.parseColor("#000000"));
    testAssignmentContentTextView.setLayoutParams(topicLayoutParams);
    android.view.View v = new android.view.View(context);
    android.widget.LinearLayout.LayoutParams viewLayoutParams = new android.widget.LinearLayout.LayoutParams(android.widget.LinearLayout.LayoutParams.MATCH_PARENT, 3);
    v.setLayoutParams(viewLayoutParams);
    v.setBackgroundColor(android.graphics.Color.parseColor("#000000"));
    /* TextView durationTextView=new TextView(context);
    durationTextView.setTextAppearance(context, android.R.style.TextAppearance_Medium);
    durationTextView.setText("Duration");
    TextView durationContentTextView=new TextView(context);
    durationContentTextView.setText(duration);
    durationContentTextView.setLayoutParams(topicLayoutParams);
     */
    parentLinearLayout.addView(topicTextView);
    parentLinearLayout.addView(objectiveTextView);
    parentLinearLayout.addView(objectiveContentTextView);
    parentLinearLayout.addView(introductionTextView);
    parentLinearLayout.addView(introContentTextView);
    parentLinearLayout.addView(questionsTextView);
    parentLinearLayout.addView(questionsContentTextView);
    parentLinearLayout.addView(activityTextView);
    parentLinearLayout.addView(activityContentTextView);
    parentLinearLayout.addView(testAssignmentTextView);
    parentLinearLayout.addView(testAssignmentContentTextView);
    parentLinearLayout.addView(v);
    /* parentLinearLayout.addView(durationTextView);
    parentLinearLayout.addView(durationContentTextView);
     */
    return parentLinearLayout;
}