protected boolean drawChild(android.graphics.Canvas canvas, android.view.View view, long j) {
    android.graphics.Canvas canvas2 = canvas;
    int width = getWidth();
    android.view.View _CVAR4 = view;
    int _CVAR3 = width;
    int _CVAR5 = _CVAR4.getWidth();
    int height = getHeight();
    float f = ((float) (height));
    android.graphics.Canvas _CVAR0 = canvas2;
    float _CVAR1 = 0.0F;
    float _CVAR2 = 0.0F;
    int _CVAR6 = ((float) (java.lang.Math.max(_CVAR3, _CVAR5)));
    float _CVAR7 = f;
    <nulltype> _CVAR8 = null;
    int _CVAR9 = 31;
    int saveLayer = _CVAR0.saveLayer(_CVAR1, _CVAR2, _CVAR6, _CVAR7, _CVAR8, _CVAR9);
    boolean drawChild = super.drawChild(canvas, view, j);
    canvas2.translate(this.mIsRTL ? ((float) (java.lang.Math.max(0, view.getWidth() - width))) : 0.0F, 0.0F);
    float f2 = ((float) (width));
    float f3 = f2 / 2.0F;
    f /= 2.0F;
    float f4 = ((float) (height - width)) / 2.0F;
    height = canvas.save();
    canvas2.rotate(90.0F, f3, f);
    canvas2.translate(0.0F, f4);
    float f5 = 0.0F - f4;
    float f6 = f2 + f4;
    canvas2.drawRect(f5, 0.0F, f6, ((float) (this.mEdgeWidth)), this.mEdgePaint);
    canvas2.restoreToCount(height);
    int save = canvas.save();
    canvas2.rotate(-90.0F, f3, f);
    canvas2.translate(0.0F, f4);
    canvas2.drawRect(f5, 0.0F, f6, ((float) (this.mEdgeWidth)), this.mEdgePaint);
    canvas2.restoreToCount(save);
    canvas2.restoreToCount(saveLayer);
    return drawChild;
}